language: php

php:
  - 5.5
  - 5.6

before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo "memory_limit = 2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer selfupdate
  - if [ ! -f app/config/security.yml ]; then ln -s security.form.yml app/config/security.yml; fi
  - composer install --no-interaction
  - composer remove --dev symfony/phpunit-bridge --no-interaction

script: bin/phpunit -c app
