<?php

namespace MpiCbg\FliesBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @author ejsmont
 * @ORM\Entity(repositoryClass=
 *             "MpiCbg\FliesBundle\Repository\CollectionBottleRepository")
 */
class FlyCage {
    
    /**
     * ID of the collection vial
     * This field is autogenerated from the barcode sequence.
     * 
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     * @ORM\SequenceGenerator(sequenceName="barcode_sequence")
     */
    protected $id; 

    /**
     * Setup date of the collection cage.
     * 
     * @ORM\Column(type="datetime", name="setup_date")
     */
    protected $setupDate;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set setupDate
     *
     * @param datetime $setupDate
     */
    public function setSetupDate($setupDate)
    {
        $this->setupDate = $setupDate;
    }

    /**
     * Get setupDate
     *
     * @return datetime $setupDate
     */
    public function getSetupDate()
    {
        return $this->setupDate;
    }
}