<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MpiCbgFliesBundleEntityFlyStockProxy extends \MpiCbg\FliesBundle\Entity\FlyStock implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function __toString()
    {
        $this->_load();
        return parent::__toString();
    }

    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->_load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->_load();
        return parent::getName();
    }

    public function getLabel()
    {
        $this->_load();
        return parent::getLabel();
    }

    public function addBVials(\MpiCbg\FliesBundle\Entity\FlyVial $vials)
    {
        $this->_load();
        return parent::addBVials($vials);
    }

    public function getVials()
    {
        $this->_load();
        return parent::getVials();
    }

    public function setSourceCross(\MpiCbg\FliesBundle\Entity\FlyCross $sourceCross)
    {
        $this->_load();
        return parent::setSourceCross($sourceCross);
    }

    public function getSourceCross()
    {
        $this->_load();
        return parent::getSourceCross();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'vials', 'sourceCross');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}