<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MpiCbgFliesBundleEntityFlyVialProxy extends \MpiCbg\FliesBundle\Entity\FlyVial implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function getLabelText()
    {
        $this->__load();
        return parent::getLabelText();
    }

    public function setSetupDate($setupDate)
    {
        $this->__load();
        return parent::setSetupDate($setupDate);
    }

    public function getSetupDate()
    {
        $this->__load();
        return parent::getSetupDate();
    }

    public function setFlipDate($flipDate)
    {
        $this->__load();
        return parent::setFlipDate($flipDate);
    }

    public function getFlipDate()
    {
        $this->__load();
        return parent::getFlipDate();
    }

    public function addChildren(\MpiCbg\FliesBundle\Entity\FlyVial $children)
    {
        $this->__load();
        return parent::addChildren($children);
    }

    public function getChildren()
    {
        $this->__load();
        return parent::getChildren();
    }

    public function setParent(\MpiCbg\FliesBundle\Entity\FlyVial $parent)
    {
        $this->__load();
        return parent::setParent($parent);
    }

    public function getParent()
    {
        $this->__load();
        return parent::getParent();
    }

    public function setStock(\MpiCbg\FliesBundle\Entity\FlyStock $stock)
    {
        $this->__load();
        return parent::setStock($stock);
    }

    public function getStock()
    {
        $this->__load();
        return parent::getStock();
    }

    public function setCross($cross)
    {
        $this->__load();
        return parent::setCross($cross);
    }

    public function getCross()
    {
        $this->__load();
        return parent::getCross();
    }

    public function getMaleCrosses()
    {
        $this->__load();
        return parent::getMaleCrosses();
    }

    public function getVirginCrosses()
    {
        $this->__load();
        return parent::getVirginCrosses();
    }

    public function getCrosses()
    {
        $this->__load();
        return parent::getCrosses();
    }

    public function isLabelPrinted()
    {
        $this->__load();
        return parent::isLabelPrinted();
    }

    public function setLabelPrinted($labelPrinted)
    {
        $this->__load();
        return parent::setLabelPrinted($labelPrinted);
    }

    public function isTrashed()
    {
        $this->__load();
        return parent::isTrashed();
    }

    public function setTrashed($trashed)
    {
        $this->__load();
        return parent::setTrashed($trashed);
    }

    public function isAlive()
    {
        $this->__load();
        return parent::isAlive();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'setupDate', 'flipDate', 'children', 'parent', 'stock', 'cross', 'maleCrosses', 'virginCrosses', 'labelPrinted', 'trashed');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}