default:
    pattern:  /
    defaults: { _controller: VIBWelcomeBundle:Default:index }
    
vib_search:
    resource: "@VIBSearchBundle/Controller/"
    type:     annotation
    prefix:   /
    
vib_forms:
    resource: "@VIBFormsBundle/Controller/"
    type:     annotation
    prefix:   /_ajax

vib_flies:
    resource: "@VIBFliesBundle/Controller/"
    type:     annotation
    prefix:   /flies

vib_antibody:
    resource: "@VIBAntibodyBundle/Controller/"
    type:     annotation
    prefix:   /antibodies

vib_calendar:
    resource: "@VIBCalendarBundle/Controller/"
    type:     annotation
    prefix:   /calendar
    
vib_users:
    resource: "@VIBUserBundle/Controller/"
    type:     annotation
    prefix:   /users

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /profile

login:
    pattern:   /login
    defaults:  { _controller: VIBImapAuthenticationBundle:Default:login }

login_check:
    pattern:   /login_check
logout:
    pattern:   /logout
