security:
    
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface:        sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: vib.user_provider.shibboleth

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~
            shibboleth: ~
            logout:
                path: /logout
                target: /
                success_handler: security.logout.handler.shibboleth

    access_control:
        - { path: ^/logout, roles: ROLE_USER, requires_channel: https }
        - { path: ^/flies, roles: ROLE_USER, requires_channel: https }
        - { path: ^/antibodies, roles: ROLE_USER, requires_channel: https }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    
    acl:
        connection: default

services:
    user_provider:
        alias: vib.user_provider.shibboleth
