<?php

/*
 * Copyright 2011 Radoslaw Kamil Ejsmont <radoslaw@ejsmont.net>
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace VIB\FliesBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use JMS\SerializerBundle\Annotation\ExclusionPolicy;
use JMS\SerializerBundle\Annotation\Expose;

/**
 * FlyCage class
 * 
 * @author Radoslaw Kamil Ejsmont <radoslaw@ejsmont.net>
 *
 * @ORM\Entity(repositoryClass="VIB\FliesBundle\Repository\CollectionBottleRepository")
 * @ExclusionPolicy("all")
*/
class FlyCage {
    
    /**
     * ID of the collection cage
     * This field is autogenerated from the barcode sequence.
     * 
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     * @ORM\SequenceGenerator(sequenceName="barcode_sequence")
     */
    protected $id; 

    /**
     * Setup date of the collection cage.
     * 
     * @ORM\Column(type="datetime", name="setup_date")
     */
    protected $setupDate;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set setupDate
     *
     * @param datetime $setupDate
     */
    public function setSetupDate($setupDate)
    {
        $this->setupDate = $setupDate;
    }

    /**
     * Get setupDate
     *
     * @return datetime
     */
    public function getSetupDate()
    {
        return $this->setupDate;
    }
}