<?php

namespace VIB\FliesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CollectionBottleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionBottleRepository extends EntityRepository
{
}