login:
  pattern:              /login
  defaults:             { _controller: IMAGLdapBundle:Default:login }
  requirements:
    _method:            GET

login_check:
  pattern:              /login_check

logout:
  pattern:              /logout
