<?php

namespace MpiCbg\FliesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CultureBottleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CultureBottleRepository extends EntityRepository
{
    private function findAllLivingQuery() {
        $date = new \DateTime();
        $date->sub(new \DateInterval('P2M'));
        
        $query = $this->createQueryBuilder('b')
            ->where('b.setupDate > :date')
            ->andWhere('b.trashed = false')
            ->setParameter('date', $date->format('d.m.y'))
            ->orderBy('b.setupDate', 'DESC')
            ->addOrderBy('b.id', 'DESC');
                
        return $query;
    }
    
    public function findAllLiving() {
        
        $query = $this->findAllLivingQuery()
            ->getQuery();               
        
        return $query->getResult();
    }
    
    public function findAllLivingStocks() {

        $query = $this->findAllLivingQuery()
            ->andWhere('b.stock is not null')
            ->getQuery();
                
        return $query->getResult();
    }
    
    public function findAllLivingCrosses() {

        $query = $this->findAllLivingQuery()
            ->andWhere('b.cross is not null')
            ->getQuery();
                
        return $query->getResult();
    }
    
}